"""add club recovery contacts

Revision ID: ba1866841896
Revises: 0caf1ce5cf65
Create Date: 2026-09-18 07:43:00.454401
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba1866841896'
down_revision: Union[str, None] = '0caf1ce5cf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('recovery_email', sa.String(length=200), nullable=True))
    op.add_column('clubs', sa.Column('recovery_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'recovery_phone')
    op.drop_column('clubs', 'recovery_email')
    # ### end Alembic commands ###
